package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Casecustomapplication generated by hbm2java
 */
public class Casecustomapplication implements java.io.Serializable {

	private Integer id;
	private Integer applicationId;
	private Integer caseId;

	public Casecustomapplication() {
	}

	public Casecustomapplication(Integer applicationId, Integer caseId) {
		this.applicationId = applicationId;
		this.caseId = caseId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

}
