package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Caseperson generated by hbm2java
 */
public class Caseperson implements java.io.Serializable {

	private Integer id;
	private Integer caseId;
	private Integer personId;

	public Caseperson() {
	}

	public Caseperson(Integer caseId, Integer personId) {
		this.caseId = caseId;
		this.personId = personId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

}
