package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Caseparticipant generated by hbm2java
 */
public class Caseparticipant implements java.io.Serializable {

	private Integer id;
	private Integer caseId;
	private Integer roleId;

	public Caseparticipant() {
	}

	public Caseparticipant(Integer caseId, Integer roleId) {
		this.caseId = caseId;
		this.roleId = roleId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Integer caseId) {
		this.caseId = caseId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
