package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Packagecustomapplication generated by hbm2java
 */
public class Packagecustomapplication implements java.io.Serializable {

	private Integer id;
	private Integer applicationId;
	private Integer packageId;

	public Packagecustomapplication() {
	}

	public Packagecustomapplication(Integer applicationId, Integer packageId) {
		this.applicationId = applicationId;
		this.packageId = packageId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

}
