package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Packageapplication generated by hbm2java
 */
public class Packageapplication implements java.io.Serializable {

	private Integer id;
	private Integer packageId;
	private Integer applicationId;

	public Packageapplication() {
	}

	public Packageapplication(Integer packageId, Integer applicationId) {
		this.packageId = packageId;
		this.applicationId = applicationId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

}
