package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Packageinherentvariable generated by hbm2java
 */
public class Packageinherentvariable implements java.io.Serializable {

	private Integer id;
	private Integer packageId;
	private Integer objectId;
	private String objectName;
	private String description;
	private Short valueType;
	private String initialValue;

	public Packageinherentvariable() {
	}

	public Packageinherentvariable(Integer packageId, Integer objectId, String objectName, String description,
			Short valueType, String initialValue) {
		this.packageId = packageId;
		this.objectId = objectId;
		this.objectName = objectName;
		this.description = description;
		this.valueType = valueType;
		this.initialValue = initialValue;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Short getValueType() {
		return this.valueType;
	}

	public void setValueType(Short valueType) {
		this.valueType = valueType;
	}

	public String getInitialValue() {
		return this.initialValue;
	}

	public void setInitialValue(String initialValue) {
		this.initialValue = initialValue;
	}

}
