package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * Processprocessecarule generated by hbm2java
 */
public class Processprocessecarule implements java.io.Serializable {

	private Integer id;
	private Integer processId;
	private Integer ruleId;
	private Integer eventId;
	private Integer conditionId;
	private String actionExpression;
	private Short repeatedTime;
	private Date activeTime;

	public Processprocessecarule() {
	}

	public Processprocessecarule(Integer processId, Integer ruleId, Integer eventId, Integer conditionId,
			String actionExpression, Short repeatedTime, Date activeTime) {
		this.processId = processId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
		this.actionExpression = actionExpression;
		this.repeatedTime = repeatedTime;
		this.activeTime = activeTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Integer getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(Integer ruleId) {
		this.ruleId = ruleId;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public Integer getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(Integer conditionId) {
		this.conditionId = conditionId;
	}

	public String getActionExpression() {
		return this.actionExpression;
	}

	public void setActionExpression(String actionExpression) {
		this.actionExpression = actionExpression;
	}

	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

	public Date getActiveTime() {
		return this.activeTime;
	}

	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}

}
