package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * Processactivityperson generated by hbm2java
 */
public class Processactivityperson implements java.io.Serializable {

	private Integer id;
	private Integer processId;
	private Integer activityId;
	private Integer roleId;
	private Integer personId;
	private Short repeatedTime;
	private Date definedStartDate;
	private Date actualStartDate;
	private Date definedEndDate;
	private Date actualEndDate;
	private Integer definedWorkload;
	private Integer actualWorkload;
	private String state;

	public Processactivityperson() {
	}

	public Processactivityperson(Integer processId, Integer activityId, Integer roleId, Integer personId,
			Short repeatedTime, Date definedStartDate, Date actualStartDate, Date definedEndDate, Date actualEndDate,
			Integer definedWorkload, Integer actualWorkload, String state) {
		this.processId = processId;
		this.activityId = activityId;
		this.roleId = roleId;
		this.personId = personId;
		this.repeatedTime = repeatedTime;
		this.definedStartDate = definedStartDate;
		this.actualStartDate = actualStartDate;
		this.definedEndDate = definedEndDate;
		this.actualEndDate = actualEndDate;
		this.definedWorkload = definedWorkload;
		this.actualWorkload = actualWorkload;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

	public Date getDefinedStartDate() {
		return this.definedStartDate;
	}

	public void setDefinedStartDate(Date definedStartDate) {
		this.definedStartDate = definedStartDate;
	}

	public Date getActualStartDate() {
		return this.actualStartDate;
	}

	public void setActualStartDate(Date actualStartDate) {
		this.actualStartDate = actualStartDate;
	}

	public Date getDefinedEndDate() {
		return this.definedEndDate;
	}

	public void setDefinedEndDate(Date definedEndDate) {
		this.definedEndDate = definedEndDate;
	}

	public Date getActualEndDate() {
		return this.actualEndDate;
	}

	public void setActualEndDate(Date actualEndDate) {
		this.actualEndDate = actualEndDate;
	}

	public Integer getDefinedWorkload() {
		return this.definedWorkload;
	}

	public void setDefinedWorkload(Integer definedWorkload) {
		this.definedWorkload = definedWorkload;
	}

	public Integer getActualWorkload() {
		return this.actualWorkload;
	}

	public void setActualWorkload(Integer actualWorkload) {
		this.actualWorkload = actualWorkload;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
