package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Processresponsibleroles generated by hbm2java
 */
public class Processresponsibleroles implements java.io.Serializable {

	private Integer id;
	private Integer processId;
	private Short functionType;
	private Integer roleId;

	public Processresponsibleroles() {
	}

	public Processresponsibleroles(Integer processId, Short functionType, Integer roleId) {
		this.processId = processId;
		this.functionType = functionType;
		this.roleId = roleId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Short getFunctionType() {
		return this.functionType;
	}

	public void setFunctionType(Short functionType) {
		this.functionType = functionType;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
