package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Processactivityresource generated by hbm2java
 */
public class Processactivityresource implements java.io.Serializable {

	private Integer id;
	private Integer processId;
	private Integer activityId;
	private Integer resourceId;
	private Short minimalNumber;
	private Short maximalNumber;
	private Short allocatedNumber;

	public Processactivityresource() {
	}

	public Processactivityresource(Integer processId, Integer activityId, Integer resourceId, Short minimalNumber,
			Short maximalNumber, Short allocatedNumber) {
		this.processId = processId;
		this.activityId = activityId;
		this.resourceId = resourceId;
		this.minimalNumber = minimalNumber;
		this.maximalNumber = maximalNumber;
		this.allocatedNumber = allocatedNumber;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	public Short getMinimalNumber() {
		return this.minimalNumber;
	}

	public void setMinimalNumber(Short minimalNumber) {
		this.minimalNumber = minimalNumber;
	}

	public Short getMaximalNumber() {
		return this.maximalNumber;
	}

	public void setMaximalNumber(Short maximalNumber) {
		this.maximalNumber = maximalNumber;
	}

	public Short getAllocatedNumber() {
		return this.allocatedNumber;
	}

	public void setAllocatedNumber(Short allocatedNumber) {
		this.allocatedNumber = allocatedNumber;
	}

}
