package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Processflowobjects generated by hbm2java
 */
public class Processflowobjects implements java.io.Serializable {

	private Integer id;
	private Integer processId;
	private Integer flowId;
	private Integer eventId;
	private Integer fromActivityId;
	private Integer toActivityId;

	public Processflowobjects() {
	}

	public Processflowobjects(Integer processId, Integer flowId, Integer eventId, Integer fromActivityId,
			Integer toActivityId) {
		this.processId = processId;
		this.flowId = flowId;
		this.eventId = eventId;
		this.fromActivityId = fromActivityId;
		this.toActivityId = toActivityId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Integer getFlowId() {
		return this.flowId;
	}

	public void setFlowId(Integer flowId) {
		this.flowId = flowId;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public Integer getFromActivityId() {
		return this.fromActivityId;
	}

	public void setFromActivityId(Integer fromActivityId) {
		this.fromActivityId = fromActivityId;
	}

	public Integer getToActivityId() {
		return this.toActivityId;
	}

	public void setToActivityId(Integer toActivityId) {
		this.toActivityId = toActivityId;
	}

}
