package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * Tasklist generated by hbm2java
 */
public class Tasklist implements java.io.Serializable {

	private Integer id;
	private Integer processId;
	private Integer activityId;
	private Integer roleId;
	private String processName;
	private String activityName;
	private String description;
	private Date definedStartDate;
	private Date definedEndDate;
	private Date actualStartDate;
	private Float completionRate;
	private String taskUrl;
	private String state;

	public Tasklist() {
	}

	public Tasklist(Integer processId, Integer activityId, Integer roleId, String processName, String activityName,
			String description, Date definedStartDate, Date definedEndDate, Date actualStartDate, Float completionRate,
			String taskUrl, String state) {
		this.processId = processId;
		this.activityId = activityId;
		this.roleId = roleId;
		this.processName = processName;
		this.activityName = activityName;
		this.description = description;
		this.definedStartDate = definedStartDate;
		this.definedEndDate = definedEndDate;
		this.actualStartDate = actualStartDate;
		this.completionRate = completionRate;
		this.taskUrl = taskUrl;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDefinedStartDate() {
		return this.definedStartDate;
	}

	public void setDefinedStartDate(Date definedStartDate) {
		this.definedStartDate = definedStartDate;
	}

	public Date getDefinedEndDate() {
		return this.definedEndDate;
	}

	public void setDefinedEndDate(Date definedEndDate) {
		this.definedEndDate = definedEndDate;
	}

	public Date getActualStartDate() {
		return this.actualStartDate;
	}

	public void setActualStartDate(Date actualStartDate) {
		this.actualStartDate = actualStartDate;
	}

	public Float getCompletionRate() {
		return this.completionRate;
	}

	public void setCompletionRate(Float completionRate) {
		this.completionRate = completionRate;
	}

	public String getTaskUrl() {
		return this.taskUrl;
	}

	public void setTaskUrl(String taskUrl) {
		this.taskUrl = taskUrl;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
