package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Webserviceparam generated by hbm2java
 */
public class Webserviceparam implements java.io.Serializable {

	private Integer id;
	private Integer applicationId;
	private Integer paramId;
	private String paramName;
	private Integer paramType;
	private String paramValue;

	public Webserviceparam() {
	}

	public Webserviceparam(Integer applicationId, Integer paramId, String paramName, Integer paramType,
			String paramValue) {
		this.applicationId = applicationId;
		this.paramId = paramId;
		this.paramName = paramName;
		this.paramType = paramType;
		this.paramValue = paramValue;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	public Integer getParamId() {
		return this.paramId;
	}

	public void setParamId(Integer paramId) {
		this.paramId = paramId;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public Integer getParamType() {
		return this.paramType;
	}

	public void setParamType(Integer paramType) {
		this.paramType = paramType;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

}
