package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * Workflowinformation generated by hbm2java
 */
public class Workflowinformation implements java.io.Serializable {

	private Integer workflowId;
	private Short workflowType;
	private Integer packageId;
	private String workflowName;
	private String description;
	private Date createDate;
	private Integer authorId;
	private Date validFrom;
	private Date validTo;
	private Short priority;
	private Integer minimalDuration;
	private Integer maximalDuration;
	private Integer twcid;
	private String graphSvgStr;
	private String graphXmlStr;
	private Integer personAllocationStrategy;
	private Boolean isValid;

	public Workflowinformation() {
	}

	public Workflowinformation(Short workflowType, Integer packageId, String workflowName, String description,
			Date createDate, Integer authorId, Date validFrom, Date validTo, Short priority, Integer minimalDuration,
			Integer maximalDuration, Integer twcid, String graphSvgStr, String graphXmlStr,
			Integer personAllocationStrategy, Boolean isValid) {
		this.workflowType = workflowType;
		this.packageId = packageId;
		this.workflowName = workflowName;
		this.description = description;
		this.createDate = createDate;
		this.authorId = authorId;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.priority = priority;
		this.minimalDuration = minimalDuration;
		this.maximalDuration = maximalDuration;
		this.twcid = twcid;
		this.graphSvgStr = graphSvgStr;
		this.graphXmlStr = graphXmlStr;
		this.personAllocationStrategy = personAllocationStrategy;
		this.isValid = isValid;
	}

	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	public Short getWorkflowType() {
		return this.workflowType;
	}

	public void setWorkflowType(Short workflowType) {
		this.workflowType = workflowType;
	}

	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	public String getWorkflowName() {
		return this.workflowName;
	}

	public void setWorkflowName(String workflowName) {
		this.workflowName = workflowName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public Short getPriority() {
		return this.priority;
	}

	public void setPriority(Short priority) {
		this.priority = priority;
	}

	public Integer getMinimalDuration() {
		return this.minimalDuration;
	}

	public void setMinimalDuration(Integer minimalDuration) {
		this.minimalDuration = minimalDuration;
	}

	public Integer getMaximalDuration() {
		return this.maximalDuration;
	}

	public void setMaximalDuration(Integer maximalDuration) {
		this.maximalDuration = maximalDuration;
	}

	public Integer getTwcid() {
		return this.twcid;
	}

	public void setTwcid(Integer twcid) {
		this.twcid = twcid;
	}

	public String getGraphSvgStr() {
		return this.graphSvgStr;
	}

	public void setGraphSvgStr(String graphSvgStr) {
		this.graphSvgStr = graphSvgStr;
	}

	public String getGraphXmlStr() {
		return this.graphXmlStr;
	}

	public void setGraphXmlStr(String graphXmlStr) {
		this.graphXmlStr = graphXmlStr;
	}

	public Integer getPersonAllocationStrategy() {
		return this.personAllocationStrategy;
	}

	public void setPersonAllocationStrategy(Integer personAllocationStrategy) {
		this.personAllocationStrategy = personAllocationStrategy;
	}

	public Boolean getIsValid() {
		return this.isValid;
	}

	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}

}
