package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Workflowcustomapplication generated by hbm2java
 */
public class Workflowcustomapplication implements java.io.Serializable {

	private Integer id;
	private Integer applicationId;
	private String description;
	private Integer workflowId;

	public Workflowcustomapplication() {
	}

	public Workflowcustomapplication(Integer applicationId, String description, Integer workflowId) {
		this.applicationId = applicationId;
		this.description = description;
		this.workflowId = workflowId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

}
