package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Workflowtwcinformation generated by hbm2java
 */
public class Workflowtwcinformation implements java.io.Serializable {

	private Integer id;
	private Integer workflowId;
	private Integer twcid;
	private Integer definedWorkload;
	private Short workloadDistributionType;
	private Float parameter1;
	private Float parameter2;
	private Float parameter3;
	private Float reduceRate;
	private Integer extraCost;

	public Workflowtwcinformation() {
	}

	public Workflowtwcinformation(Integer workflowId, Integer twcid, Integer definedWorkload,
			Short workloadDistributionType, Float parameter1, Float parameter2, Float parameter3, Float reduceRate,
			Integer extraCost) {
		this.workflowId = workflowId;
		this.twcid = twcid;
		this.definedWorkload = definedWorkload;
		this.workloadDistributionType = workloadDistributionType;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.reduceRate = reduceRate;
		this.extraCost = extraCost;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	public Integer getTwcid() {
		return this.twcid;
	}

	public void setTwcid(Integer twcid) {
		this.twcid = twcid;
	}

	public Integer getDefinedWorkload() {
		return this.definedWorkload;
	}

	public void setDefinedWorkload(Integer definedWorkload) {
		this.definedWorkload = definedWorkload;
	}

	public Short getWorkloadDistributionType() {
		return this.workloadDistributionType;
	}

	public void setWorkloadDistributionType(Short workloadDistributionType) {
		this.workloadDistributionType = workloadDistributionType;
	}

	public Float getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(Float parameter1) {
		this.parameter1 = parameter1;
	}

	public Float getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(Float parameter2) {
		this.parameter2 = parameter2;
	}

	public Float getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(Float parameter3) {
		this.parameter3 = parameter3;
	}

	public Float getReduceRate() {
		return this.reduceRate;
	}

	public void setReduceRate(Float reduceRate) {
		this.reduceRate = reduceRate;
	}

	public Integer getExtraCost() {
		return this.extraCost;
	}

	public void setExtraCost(Integer extraCost) {
		this.extraCost = extraCost;
	}

}
