package com.winginrian.hibernate.dto;
// Generated 2019-3-20 0:37:34 by Hibernate Tools 5.2.11.Final

/**
 * Workflowactivityinvokingworkflow generated by hbm2java
 */
public class Workflowactivityinvokingworkflow implements java.io.Serializable {

	private Integer id;
	private Integer workflowId;
	private Integer activityId;
	private Integer invokedWorkflowId;
	private Short invocationType;
	private Short invocationMethod;

	public Workflowactivityinvokingworkflow() {
	}

	public Workflowactivityinvokingworkflow(Integer workflowId, Integer activityId, Integer invokedWorkflowId,
			Short invocationType, Short invocationMethod) {
		this.workflowId = workflowId;
		this.activityId = activityId;
		this.invokedWorkflowId = invokedWorkflowId;
		this.invocationType = invocationType;
		this.invocationMethod = invocationMethod;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public Integer getInvokedWorkflowId() {
		return this.invokedWorkflowId;
	}

	public void setInvokedWorkflowId(Integer invokedWorkflowId) {
		this.invokedWorkflowId = invokedWorkflowId;
	}

	public Short getInvocationType() {
		return this.invocationType;
	}

	public void setInvocationType(Short invocationType) {
		this.invocationType = invocationType;
	}

	public Short getInvocationMethod() {
		return this.invocationMethod;
	}

	public void setInvocationMethod(Short invocationMethod) {
		this.invocationMethod = invocationMethod;
	}

}
